
main:
  file_lists:
    input_db_dir: "/home/kremeto1/neural_rendering/datasets/final/imc/pantheon_exterior_thesis_test_squarify-100_src-fused_inloc_format/cutouts"
    input_db_glob: "cutout_*.png"
    input_query_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/imc/pantheon_exterior_thesis_test_squarify-100_src-fused/test"
    input_query_glob: "*_reference.png"
    output_db_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/db_imgnames_all.mat"
    output_query_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_imgnames_all.mat"

  features:
    input_netvlad_pretrained: "/home/lucivpav/NetVLAD/vd16_pitts30k_conv5_3_vlad_preL2_intra_white.mat"
    input_db_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/db_imgnames_all.mat"
    input_query_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_imgnames_all.mat"
    output_db_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/db_features/"
    output_query_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_features/"
    input_feature_layer: 5

  scores:
    input_db_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/db_features/"
    input_query_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_features/"
    output_scores_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/scores.mat"
    input_feature_layer: 5

  retrieval:
    input_scores_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/scores.mat"
    input_topN: 100
    output_topN_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/original_top100_shortlist.mat"

  pose_estimation:
    input_pnp_topN: 10
    input_query_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_features/"
    input_db_features_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/db_features/"
    input_topN_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/original_top100_shortlist.mat"
    input_transforms_path: "/home/kremeto1/neural_rendering/datasets/final/imc/pantheon_exterior_thesis_spheres_squarify-100_src-fused_inloc_format/poses"
    input_cutout_matfiles_path: "/home/kremeto1/neural_rendering/datasets/final/imc/pantheon_exterior_thesis_spheres_squarify-100_src-fused_inloc_format/matfiles"
    output_candidate_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/densePE_top100_shortlist.mat"
    output_gv_dense_dir: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/gv_dense"
    output_pnp_dense_inlier_dir: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/pnp_dense_inlier"
    input_feature_layer: 5

  pose_verification:
    input_candidate_pose_renders_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/candidate_renders"
    input_candidate_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/densePE_top100_shortlist.mat"
    output_shortlist_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/densePV_top10_shortlist.mat"

  evaluation:
    root_to_process: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-spheres/"
    input_query_mat_path: "/home/kremeto1/inloc/datasets/pipeline-pantheon-conv5-pyrender/query_imgnames_all.mat"
