bdechamps_model:
  input:
    dir: '/home/kremeto1/neural_rendering/inferences/inloc/query_rendered_scaled'
    topK_matfile: 'outputs/densePE_top100_shortlist.mat'
    imgformat: '.png'

  output:
    dir: 'outputs'
    txtname: 'neuralPV_with mask.txt'
    matname: 'neuralPV_with_mask.mat'
    synth_dir: "fullfile(params.output.dir, 'synthesized')"  # View synthesis results (directory)
    synth_matformat: '.synth.mat'  # View synthesis results (file extention)

pantheon:
  file_lists:
    input_db_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/imc/pantheon_exterior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson/train"
    input_db_glob: "*_reference.png"
    input_db_depth_glob: "*_depth.npy"
    input_query_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/imc/pantheon_exterior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson/val"
    input_query_glob: "*_reference.png"
    output_db_mat_path: "/home/kremeto1/inloc/datasets/pantheon/db_imgnames_all.mat"
    output_db_depth_mat_path: "/home/kremeto1/inloc/datasets/pantheon/db_depthnames_all.mat"
    output_query_mat_path: "/home/kremeto1/inloc/datasets/pantheon/query_imgnames_all.mat"

  features:
    input_netvlad_pretrained: "/home/lucivpav/NetVLAD/vd16_pitts30k_conv5_3_vlad_preL2_intra_white.mat"
    input_db_mat_path: "/home/kremeto1/inloc/datasets/pantheon/db_imgnames_all.mat"
    input_query_mat_path: "/home/kremeto1/inloc/datasets/pantheon/query_imgnames_all.mat"
    output_features_mat_path: "/home/kremeto1/inloc/datasets/pantheon/computed_features.mat"

  scores:
    input_features_mat_path: "/home/kremeto1/inloc/datasets/pantheon/computed_features.mat"
    output_scores_mat_path: "/home/kremeto1/inloc/datasets/pantheon/scores.mat"

  retrieval:
    input_db_mat_path: "/home/kremeto1/inloc/datasets/pantheon/db_imgnames_all.mat"
    input_query_mat_path: "/home/kremeto1/inloc/datasets/pantheon/query_imgnames_all.mat"
    input_scores_mat_path: "/home/kremeto1/inloc/datasets/pantheon/scores.mat"
    output_top100_mat_path: "/home/kremeto1/inloc/datasets/pantheon/original_top100_shortlist.mat"

  pose_estimation:
    input_features_mat_path: "/home/kremeto1/inloc/datasets/pantheon/computed_features.mat"
    input_top100_mat_path: "/home/kremeto1/inloc/datasets/pantheon/original_top100_shortlist.mat"
    input_db_depth_mat_path: "/home/kremeto1/inloc/datasets/pantheon/db_depthnames_all.mat"
    input_transforms_path: "/home/kremeto1/neural_rendering/datasets/processed/imc/pantheon_exterior/dense/dense/sparse"
    output_candidate_mat_path: "/home/kremeto1/inloc/datasets/pantheon/densePE_top100_shortlist.mat"
    output_gv_dense_dir: "/home/kremeto1/inloc/datasets/pantheon/gv_dense"
    output_pnp_dense_inlier_dir: "/home/kremeto1/inloc/datasets/pantheon/pnp_dense_inlier"

  # input:
  #   dir: '/home/kremeto1/neural_rendering/inferences/inloc/pantheon'
  #   topK_matfile: 'outputs/densePE_top100_shortlist.mat'
  #   imgformat: '.png'

  # output:
  #   dir: '/home/kremeto1/neural_rendering/inferences/inloc/pantheon/outputs'
  #   txtname: 'neuralPV_with mask.txt'
  #   matname: 'neuralPV_with_mask.mat'
  #   synth_dir: "fullfile(params.output.dir, 'synthesized')"  # View synthesis results (directory)
  #   synth_matformat: '.synth.mat'  # View synthesis results (file extention)
