bdechamps_model:
  input:
    dir: '/home/kremeto1/neural_rendering/inferences/inloc/query_rendered_scaled'
    topK_matfile: 'outputs/densePE_top100_shortlist.mat'
    imgformat: '.png'

  output:
    dir: 'outputs'
    txtname: 'neuralPV_with mask.txt'
    matname: 'neuralPV_with_mask.mat'
    synth_dir: "fullfile(params.output.dir, 'synthesized')"  # View synthesis results (directory)
    synth_matformat: '.synth.mat'  # View synthesis results (file extention)

artwin:
  file_lists:
    input_db_dir: "/nfs/projects/artwin/experiments/hololens_mapper/joined_dataset/train"
    input_db_glob: "*_reference.png"
    input_query_dir: "/nfs/projects/artwin/experiments/hololens_mapper/joined_dataset/test"
    input_query_glob: "*_reference.png"
    output_db_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_imgpaths.mat"
    output_query_mat_path: "/home/kremeto1/inloc/datasets/artwin/query_imgpaths.mat"

  features:
    input_netvlad_pretrained: "/home/lucivpav/NetVLAD/vd16_pitts30k_conv5_3_vlad_preL2_intra_white.mat"
    input_db_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_imgpaths.mat"
    input_query_mat_path: "/home/kremeto1/inloc/datasets/artwin/query_imgpaths.mat"
    output_db_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_features.mat"
    output_query_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/query_features.mat"

  scores:
    input_db_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_features.mat"
    input_query_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/query_features.mat"
    output_scores_mat_path: "/home/kremeto1/inloc/datasets/artwin/scores.mat"

  retrieval:
    input_scores_mat_path: "/home/kremeto1/inloc/datasets/artwin/scores.mat"
    input_topN: 20  # TODO 100
    output_topN_mat_path: "/home/kremeto1/inloc/datasets/artwin/original_top100_shortlist.mat"

  pose_estimation:
    input_pnp_topN: 10
    input_query_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/query_features.mat"
    input_db_features_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_features.mat"
    input_topN_mat_path: "/home/kremeto1/inloc/datasets/artwin/original_top100_shortlist.mat"
    # input_db_depth_mat_path: "/home/kremeto1/inloc/datasets/artwin/db_depthnames_all.mat"
    input_transforms_path: "/nfs/projects/artwin/experiments/artwin-inloc/joined_dataset_train/poses"
    input_cutout_matfiles_path: "/nfs/projects/artwin/experiments/artwin-inloc/joined_dataset_train/matfiles"
    output_candidate_mat_path: "/home/kremeto1/inloc/datasets/artwin/densePE_top100_shortlist.mat"
    output_gv_dense_dir: "/home/kremeto1/inloc/datasets/artwin/gv_dense"
    output_pnp_dense_inlier_dir: "/home/kremeto1/inloc/datasets/artwin/pnp_dense_inlier"

  pose_verification:
    input_candidate_mat_path: "/home/kremeto1/inloc/datasets/artwin/densePE_top100_shortlist.mat"
    output_shortlist_mat_path: "/home/kremeto1/inloc/datasets/artwin/densePV_top10_shortlist.mat"
    # TODO rendered images path and glob
